"use client";
import Head from "next/head";
import { useTransition} from "react";
import TabButton from "../components/TabButton";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillMail,

} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import first from "../public/Sabah.png";
import second from "../public/SabahAbout.png"
import auction from "../public/auction.png";
import balance from "../public/balance.png";
import gavel from "../public/gavel.png";
import compliant from "../public/compliant.png"
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import EmailSection from "../components/EmailSection";


const TAB_DATA = [
  {
    title: "Skills",
    id: "skills",
    content: (
      <ul className="list-disc pl-4 text-justify">
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Legal Research:</span> Proficient in conducting comprehensive legal research using various resources such as LexisNexis, Westlaw, and academic databases to support case preparation and legal analysis.</li>
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Legal Writing:</span> Skilled in drafting a wide range of legal documents, including briefs, motions, pleadings, contracts, and legal memoranda, with a keen eye for detail and adherence to legal standards and conventions.</li>
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Analytical Skills:</span> Demonstrated ability to analyze complex legal issues, identify relevant statutes, regulations, and case law, and apply legal principles to formulate sound legal arguments and strategies.</li>
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Communication Skills:</span> Strong oral and written communication skills, including the ability to articulate legal concepts clearly and persuasively to clients, colleagues, and stakeholders. Experience in negotiation and effective advocacy before courts, arbitrators, and mediators.</li>
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Problem-Solving: </span>Proven track record of developing innovative and practical solutions to legal challenges, with a focus on achieving favorable outcomes for clients while managing risks effectively.</li>
        <li className="pb-4"> <span className="text-[#D5A848] font-semibold">Attention to Detail: </span>Meticulous in reviewing legal documents, contracts, and agreements to ensure accuracy, completeness, and compliance with legal requirements and client instructions.</li>
      </ul>
    ),
  },
  {
    title: "Education",
    id: "education",
    content: (
      <ul className="list-disc pl-4">
        <li className="pb-2">Fullstack Academy of Code</li>
        <li className="pb-2">University of California, Santa Cruz</li>
      </ul >
    ),
  },
  {
    title: "Certifications",
    id: "certifications",
    content: (
      <ul className="list-disc pl-4">
        <li>AWS Cloud Practitioner</li>
        <li>Google Professional Cloud Developer</li>
      </ul>
    ),
  },
];


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const [tab, setTab] = useState("skills");
  const [isPending, startTransition] = useTransition();

  const handleTabChange = (id) => {
    startTransition(() => {
      setTab(id);
    });
  };
  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="mb-24">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">PROSECUTOR</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-[#D5A848] text- to-[#e9b953] text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center flex flex-wrap justify-center">
            <div className="mb-8">
              <h2 className="text-5xl py-2 text-[#D5A848] font-medium dark:text-[#D5A848] md:text-6xl">
                <span className="dark:text-white text-black">Ms. Sabah </span> M. Adem
              </h2>
              <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
                <span className="dark:text-[#D5A848] text-[#D5A848]">Senior</span> Prosecutor 
              </h3>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
                A self-driven result-oriented professional that believes in excellence and hard work with a proven track record in handling and successfully prosecuting challenging legal cases.
              </p>
              <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                <a href="https://www.linkedin.com/in/ms-sabah-m-adem-503050241/" className=""><AiFillTwitterCircle className="dark:hover:text-[#D5A848] hover:text-[#D5A848]" /></a>
                <a href="https://www.linkedin.com/in/ms-sabah-m-adem-503050241/"><AiFillLinkedin className="dark:hover:text-[#D5A848] hover:text-[#D5A848]"/> </a>
                <a href="mailto:example@example.com"><AiFillMail className="dark:hover:text-[#D5A848] hover:text-[#D5A848]"/></a>
              </div>
            </div>
            
            <div className="mx-auto bg-gradient-to-b  from-[#D5A848] rounded-full relative overflow-hidden mt-20 sm:mt-0 md:h-96 md:w-96">
              <Image src={first}  objectFit="cover" style={{ marginTop: '30px' }} />
            </div>
          </div>
        </section>
        <section className="mb-14">
          <div className="md:mb-12">
            <h3 className="text-5xl psy-1  dark:text-white text-black  ">About <span className="text-[#D5A848]">Me</span></h3>
            
          </div>
          <div className="flex flex-wrap ">

            {/* <div className="bg-gradient-to-b  from-transparent to-[#D5A848] md:h-96 md:w-96">
              <Image src={second} 
                className="rounded-lg object-contain"
                width={"100%"}
                height={"100%"}
                layout="responsive"/>
            </div> */}

            <div className="items-center text-justify align-middle content-center">
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 mx-auto md:text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, id. Fugiat vero porro illum incidunt similique veniam atque explicabo rerum vel ut. Facilis cumque aliquam suscipit quo libero, similique ut. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur fugiat earum adipisci autem, iste tenetur repellat explicabo ea. Temporibus dolorum praesentium commodi rem. Ab totam odio repudiandae aut culpa explicabo.</p>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 mx-auto md:text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa provident quos necessitatibus corporis molestiae corrupti eaque explicabo, numquam cum, deserunt, sed architecto voluptas nemo? Quas voluptatem in distinctio aspernatur minus!</p>
              <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 mx-auto md:text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa provident quos necessitatibus corporis molestiae corrupti eaque explicabo, numquam cum, deserunt, sed architecto voluptas nemo? Quas voluptatem in distinctio aspernatur minus!</p>
              <button className="bg-gradient-to-r from-[#D5A848] text- to-[#e9b953] text-white px-4 py-2 border-none rounded-md"> Know More</button>
            </div>
            <div className="">
              <div className="flex flex-row justify-start mt-8">
                <TabButton
                  selectTab={() => handleTabChange("skills")}
                  active={tab === "skills"}
                >
                  {" "}
                  Skills{" "}
                </TabButton>
                <TabButton
                  selectTab={() => handleTabChange("education")}
                  active={tab === "education"}
                >
                  {" "}
                  Education{" "}
                </TabButton>
                <TabButton
                  selectTab={() => handleTabChange("certifications")}
                  active={tab === "certifications"}
                >
                  {" "}
                  Certifications{" "}
                </TabButton>
            </div>
            <div className="mt-8 dark:text-white">
              {TAB_DATA.find((t) => t.id === tab).content}
            </div>
          </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl psy-1  text-[#D5A848]  ">Services <span className="dark:text-white text-black">I offer</span></h3>
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={balance} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={auction} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={gavel} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>

            
            
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={compliant} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={balance} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 h-auto border bg-white border-[#D5A848] flex-1  transition duration-300 ease-in-out transform hover:scale-105 hover:shadow-xl">
              <Image src={auction} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Beautiful Designs
              </h3>
              <p className="py-2 ">
                Creating elegant designs suited for your needs following core design theory.
              </p>
            </div>
            
            
          </div>
        </section>
        <section className="">
          <div className="">
            <h3 className="text-5xl psy-1  dark:text-white text-black">Contact <span className=" text-[#D5A848]  ">Me</span></h3>
            
          </div>
            <EmailSection/>
          
        </section>
      </main>
    </div>
  );
}
